### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by ishin318** [nagataaaas/Jusho#1]
from jusho import Jusho
で「'type' object is not subscriptable」というエラーが発生する。
コードはキータにあるコードです。
```
from jusho import Jusho

postman = Jusho()

print(postman.from_postal_code('160-0021'))
```

**Comment by nagataaaas** [comment]
おそらく、Python3.9未満ではないでしょうか。Pythonのバージョンや環境を合わせて記述していただけると助かります。

Python3.9以上から認められる気法を用いていたことが原因でした。

3.8以下でエラーが出ないように書き直しましたので、0.0.2にアップデートしてご利用ください。

**Comment by ishin318** [comment]
0.0.2にアップデートして試してみましたが以下のエラーが出ました。
```
Union[arg, ...]: each arg must be a type. Got [None].
```

というエラーが出ました。
なのでPythonを3.9.1にアップデートしましたが、同じエラーでダメでした。

**Comment by nagataaaas** [comment]
申し訳ないです。

0.0.3で修正しました。
