### ISSUE TITLE
pipでインストール時にaddress.dbが含まれない

### ISSUE THREAD

**Issue by namuyan** [nagataaaas/Jusho#3]
英語で書くべきなのだろうけど、日本の住所索引だしこれで失礼します。

pipパッケージよりwhlをインストールしましたがaddress.dbが含まれません。
正確にはパッケージに含まれますがインストール時に取りこぼされています。

対応の方をよろしくお願いします。

Ubuntu20.04 Python3.8.2 64bits

**Comment by nagataaaas** [comment]
testをWindows端末で行っているのですが、Linuxの一部の環境で
- `sys.prefix`が少し変なディレクトリを指す可能性がある
- Windowsに対して、パッケージディレクトリの深さが違う場合がある
という問題があったため発生していました。

バージョン0.0.4で修正されたと思いますので、ご確認下さい。
WSLのUbuntu 20.04で確認しました。

**Comment by namuyan** [comment]
早い対応をしていただきありがとうございます！
問題なくaddress.dbを取り込むことができました。

https://github.com/nagataaaas/Jusho/commit/73dde29614664815e19e54f662371af18e8ad826#diff-443ba60a54f8c45a78feb94d4d2bbcc821b3d7ae6aa3d90b931ff7e47d3b718cR64
テスト用のprint文がJushoクラス作成時に出力されますね？
とりあえず問題は解決しており害はないのでCloseさせて頂きます。

**Comment by nagataaaas** [comment]
確認ありがとうございます。

すみません、printを消すのを失念しておりました。。。
0.0.5で削除しました m _ _ m

ありがとうございました
